-- The domain's records (DOMAIN.md › Entities), one table per entity.
--
-- - Every record belongs to one workspace. References are composite foreign
--   keys on (workspace_id, id), so a record can only point at records in the
--   same workspace (the rule `findIntegrityViolations` checks in TypeScript).
-- - Check constraints mirror the Zod schemas' invariants, so no write path can
--   store what the domain would reject.
-- - Derived state (Today, outreach state, timing groups, company aggregates)
--   is never stored.
-- - References between records never cascade: deleting something that history
--   points at fails. Only removing a whole workspace (with its account)
--   removes its records.
-- - Ids are random UUIDs, generated by the application before writing, so
--   related records can be created together and nothing sequential is exposed.

create table public.companies (
  id uuid primary key,
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  name text not null check (btrim(name) <> ''),
  -- DOMAIN.md › Company: names are unique per user, ignoring case and whitespace.
  name_key text generated always as (lower(regexp_replace(btrim(name), '\s+', ' ', 'g'))) stored,
  website text check (btrim(website) <> ''),
  sector text check (btrim(sector) <> ''),
  location text check (btrim(location) <> ''),
  notes text,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  constraint companies_workspace_id_key unique (workspace_id, id),
  constraint companies_unique_name unique (workspace_id, name_key)
);

create table public.people (
  id uuid primary key,
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  name text not null check (btrim(name) <> ''),
  role text check (btrim(role) <> ''),
  company_id uuid,
  source_kind text not null check (
    source_kind in (
      'alumni_network', 'event', 'linkedin', 'company_website',
      'university', 'publication', 'introduction', 'other'
    )
  ),
  source_detail text check (btrim(source_detail) <> ''),
  email text check (position('@' in email) > 1),
  -- A link only; never fetched (D-005).
  linkedin_url text check (
    linkedin_url ~* '^[a-z][a-z0-9+.-]*://([^/?#@]*@)?([a-z0-9-]+\.)*linkedin\.com(:[0-9]+)?([/?#]|$)'
  ),
  location text check (btrim(location) <> ''),
  why_relevant text check (btrim(why_relevant) <> ''),
  notes text,
  relationship_status text not null check (
    relationship_status in ('new', 'contacted', 'replied', 'warm', 'dormant')
  ),
  preferred_channel text check (preferred_channel in ('email', 'linkedin', 'other')),
  outreach_closed_at timestamptz,
  outreach_closure_reason text check (
    outreach_closure_reason in ('no_response', 'not_a_fit', 'completed')
  ),
  created_at timestamptz not null,
  updated_at timestamptz not null,
  constraint people_workspace_id_key unique (workspace_id, id),
  constraint people_company_fkey foreign key (workspace_id, company_id)
    references public.companies (workspace_id, id),
  constraint people_needs_context check (role is not null or company_id is not null),
  constraint people_closure_complete check (
    num_nonnulls(outreach_closed_at, outreach_closure_reason) in (0, 2)
  )
);
create index people_company_idx on public.people (workspace_id, company_id);

create table public.opportunities (
  id uuid primary key,
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  title text not null check (btrim(title) <> ''),
  company_id uuid not null,
  status text not null check (
    status in (
      'identified', 'researching', 'reaching_out', 'applied', 'interviewing', 'offer', 'closed'
    )
  ),
  closed_reason text check (
    closed_reason in ('accepted', 'declined', 'rejected', 'withdrawn', 'no_response', 'expired')
  ),
  type text check (
    type in (
      'internship', 'graduate_role', 'startup_role', 'research', 'mentorship', 'referral', 'other'
    )
  ),
  priority text check (priority in ('high', 'medium', 'low')),
  deadline date,
  url text check (btrim(url) <> ''),
  notes text,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  constraint opportunities_workspace_id_key unique (workspace_id, id),
  constraint opportunities_company_fkey foreign key (workspace_id, company_id)
    references public.companies (workspace_id, id),
  constraint opportunities_closed_reason check ((status = 'closed') = (closed_reason is not null))
);
create index opportunities_company_idx on public.opportunities (workspace_id, company_id);

-- Opportunity.personIds, in order. A person is linked at most once.
create table public.opportunity_people (
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  opportunity_id uuid not null,
  person_id uuid not null,
  position smallint not null check (position >= 0),
  primary key (opportunity_id, person_id),
  constraint opportunity_people_opportunity_fkey foreign key (workspace_id, opportunity_id)
    references public.opportunities (workspace_id, id) on delete cascade,
  constraint opportunity_people_person_fkey foreign key (workspace_id, person_id)
    references public.people (workspace_id, id)
);
create index opportunity_people_person_idx on public.opportunity_people (workspace_id, person_id);

create table public.interactions (
  id uuid primary key,
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  person_id uuid not null,
  opportunity_id uuid,
  kind text not null check (kind in ('message_sent', 'message_received', 'meeting', 'note')),
  occurred_at timestamptz not null,
  summary text not null check (btrim(summary) <> ''),
  channel text check (channel in ('email', 'linkedin', 'other')),
  subject text check (btrim(subject) <> ''),
  body text check (btrim(body) <> ''),
  format text check (format in ('in_person', 'video', 'phone')),
  created_at timestamptz not null,
  updated_at timestamptz not null,
  constraint interactions_workspace_id_key unique (workspace_id, id),
  -- Lets a sent draft prove it points at a message_sent to the same person.
  constraint interactions_sent_message_key unique (workspace_id, id, person_id, kind),
  constraint interactions_person_fkey foreign key (workspace_id, person_id)
    references public.people (workspace_id, id),
  constraint interactions_opportunity_fkey foreign key (workspace_id, opportunity_id)
    references public.opportunities (workspace_id, id),
  constraint interactions_kind_fields check (
    case kind
      when 'meeting' then format is not null and num_nulls(channel, subject, body) = 3
      when 'note' then num_nulls(channel, subject, body, format) = 4
      else channel is not null and format is null
    end
  )
);
create index interactions_person_idx on public.interactions (workspace_id, person_id, occurred_at);
create index interactions_opportunity_idx on public.interactions (workspace_id, opportunity_id);

create table public.drafts (
  id uuid primary key,
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  person_id uuid not null,
  opportunity_id uuid,
  channel text not null check (channel in ('email', 'linkedin', 'other')),
  subject text check (btrim(subject) <> ''),
  body text not null check (btrim(body) <> ''),
  origin text not null check (origin in ('user', 'generated')),
  status text not null check (status in ('awaiting_approval', 'approved', 'sent', 'discarded')),
  approved_at timestamptz,
  sent_at timestamptz,
  sent_interaction_id uuid unique,
  sent_kind text generated always as (
    case when sent_interaction_id is not null then 'message_sent' end
  ) stored,
  discarded_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  constraint drafts_workspace_id_key unique (workspace_id, id),
  constraint drafts_person_fkey foreign key (workspace_id, person_id)
    references public.people (workspace_id, id),
  constraint drafts_opportunity_fkey foreign key (workspace_id, opportunity_id)
    references public.opportunities (workspace_id, id),
  -- A sent draft points at the message_sent it became, to the same person.
  constraint drafts_sent_interaction_fkey
    foreign key (workspace_id, sent_interaction_id, person_id, sent_kind)
    references public.interactions (workspace_id, id, person_id, kind),
  -- The approval gate (D-011): each status carries exactly its own fields, so
  -- nothing is sent without having been approved.
  constraint drafts_status_fields check (
    case status
      when 'awaiting_approval' then num_nulls(approved_at, sent_at, sent_interaction_id, discarded_at) = 4
      when 'approved' then approved_at is not null and num_nulls(sent_at, sent_interaction_id, discarded_at) = 3
      when 'sent' then num_nonnulls(approved_at, sent_at, sent_interaction_id) = 3 and discarded_at is null
      when 'discarded' then discarded_at is not null and num_nulls(approved_at, sent_at, sent_interaction_id) = 3
    end
  ),
  constraint drafts_email_subject check (
    channel <> 'email' or status not in ('approved', 'sent') or subject is not null
  )
);
create index drafts_person_idx on public.drafts (workspace_id, person_id, status);
create index drafts_opportunity_idx on public.drafts (workspace_id, opportunity_id);

create table public.next_actions (
  id uuid primary key,
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  kind text not null check (
    kind in ('follow_up', 'reach_out', 'apply', 'prepare', 'research', 'other')
  ),
  title text not null check (btrim(title) <> ''),
  person_id uuid,
  opportunity_id uuid,
  interaction_id uuid,
  due_on date not null,
  status text not null check (status in ('open', 'done', 'dismissed')),
  completed_at timestamptz,
  dismissed_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  constraint next_actions_workspace_id_key unique (workspace_id, id),
  constraint next_actions_person_fkey foreign key (workspace_id, person_id)
    references public.people (workspace_id, id),
  constraint next_actions_opportunity_fkey foreign key (workspace_id, opportunity_id)
    references public.opportunities (workspace_id, id),
  constraint next_actions_interaction_fkey foreign key (workspace_id, interaction_id)
    references public.interactions (workspace_id, id),
  constraint next_actions_attached check (person_id is not null or opportunity_id is not null),
  constraint next_actions_follow_up_names_person check (kind <> 'follow_up' or person_id is not null),
  constraint next_actions_status_fields check (
    case status
      when 'open' then num_nulls(completed_at, dismissed_at) = 2
      when 'done' then completed_at is not null and dismissed_at is null
      when 'dismissed' then dismissed_at is not null and completed_at is null
    end
  )
);
-- DOMAIN.md › NextAction: a person has at most one open follow-up.
create unique index next_actions_one_open_follow_up
  on public.next_actions (workspace_id, person_id)
  where status = 'open' and kind = 'follow_up';
create index next_actions_due_idx on public.next_actions (workspace_id, status, due_on);
create index next_actions_person_idx on public.next_actions (workspace_id, person_id);
create index next_actions_opportunity_idx on public.next_actions (workspace_id, opportunity_id);
create index next_actions_interaction_idx on public.next_actions (workspace_id, interaction_id);

-- Research context (DOMAIN.md › Research context). A subject is exactly one
-- person, company or opportunity, each with a real foreign key.
create table public.source_facts (
  id uuid primary key,
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  subject_type text not null check (subject_type in ('person', 'company', 'opportunity')),
  person_id uuid,
  company_id uuid,
  opportunity_id uuid,
  statement text not null check (btrim(statement) <> ''),
  provenance_kind text not null check (
    provenance_kind in (
      'public_profile', 'company_website', 'university_website', 'publication',
      'event', 'correspondence', 'other'
    )
  ),
  provenance_url text check (btrim(provenance_url) <> ''),
  provenance_detail text check (btrim(provenance_detail) <> ''),
  observed_on date,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  constraint source_facts_workspace_id_key unique (workspace_id, id),
  constraint source_facts_person_fkey foreign key (workspace_id, person_id)
    references public.people (workspace_id, id),
  constraint source_facts_company_fkey foreign key (workspace_id, company_id)
    references public.companies (workspace_id, id),
  constraint source_facts_opportunity_fkey foreign key (workspace_id, opportunity_id)
    references public.opportunities (workspace_id, id),
  constraint source_facts_one_subject check (
    case subject_type
      when 'person' then person_id is not null and num_nulls(company_id, opportunity_id) = 2
      when 'company' then company_id is not null and num_nulls(person_id, opportunity_id) = 2
      when 'opportunity' then opportunity_id is not null and num_nulls(person_id, company_id) = 2
    end
  )
);
create index source_facts_person_idx on public.source_facts (workspace_id, person_id);
create index source_facts_company_idx on public.source_facts (workspace_id, company_id);
create index source_facts_opportunity_idx on public.source_facts (workspace_id, opportunity_id);

-- Generated reasoning, labelled and cited (D-009). Representable now; nothing
-- in Reachout generates it yet (D-022).
create table public.interpretations (
  id uuid primary key,
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  subject_type text not null check (subject_type in ('person', 'company', 'opportunity')),
  person_id uuid,
  company_id uuid,
  opportunity_id uuid,
  kind text not null check (
    kind in ('relevance', 'outreach_angle', 'summary', 'follow_up_suggestion')
  ),
  text text not null check (btrim(text) <> ''),
  generated_by_kind text not null check (generated_by_kind in ('model', 'rule')),
  generated_by_name text not null check (btrim(generated_by_name) <> ''),
  generated_at timestamptz not null,
  review text not null check (review in ('suggested', 'accepted', 'dismissed')),
  created_at timestamptz not null,
  updated_at timestamptz not null,
  constraint interpretations_workspace_id_key unique (workspace_id, id),
  constraint interpretations_person_fkey foreign key (workspace_id, person_id)
    references public.people (workspace_id, id),
  constraint interpretations_company_fkey foreign key (workspace_id, company_id)
    references public.companies (workspace_id, id),
  constraint interpretations_opportunity_fkey foreign key (workspace_id, opportunity_id)
    references public.opportunities (workspace_id, id),
  constraint interpretations_one_subject check (
    case subject_type
      when 'person' then person_id is not null and num_nulls(company_id, opportunity_id) = 2
      when 'company' then company_id is not null and num_nulls(person_id, opportunity_id) = 2
      when 'opportunity' then opportunity_id is not null and num_nulls(person_id, company_id) = 2
    end
  )
);
create index interpretations_person_idx on public.interpretations (workspace_id, person_id);
create index interpretations_company_idx on public.interpretations (workspace_id, company_id);
create index interpretations_opportunity_idx on public.interpretations (workspace_id, opportunity_id);

-- Interpretation.basedOnFactIds, in order.
create table public.interpretation_facts (
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  interpretation_id uuid not null,
  fact_id uuid not null,
  position smallint not null check (position >= 0),
  primary key (interpretation_id, fact_id),
  constraint interpretation_facts_interpretation_fkey foreign key (workspace_id, interpretation_id)
    references public.interpretations (workspace_id, id) on delete cascade,
  constraint interpretation_facts_fact_fkey foreign key (workspace_id, fact_id)
    references public.source_facts (workspace_id, id)
);
create index interpretation_facts_fact_idx on public.interpretation_facts (workspace_id, fact_id);

/* ——— Access: members read their workspace; only the writer role writes ——— */

do $$
declare
  t text;
begin
  foreach t in array array[
    'companies', 'people', 'opportunities', 'opportunity_people', 'interactions',
    'drafts', 'next_actions', 'source_facts', 'interpretations', 'interpretation_facts'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format(
      'create policy "Members can read their workspace''s records" on public.%I '
      'for select to authenticated, reachout_writer '
      'using (workspace_id in (select private.member_workspaces()))',
      t
    );
    execute format(
      'create policy "Writes stay inside the member''s workspace" on public.%I '
      'for all to reachout_writer '
      'using (workspace_id in (select private.member_workspaces())) '
      'with check (workspace_id in (select private.member_workspaces()))',
      t
    );
    execute format('revoke all on public.%I from public, anon, authenticated', t);
    execute format('grant select on public.%I to authenticated', t);
    execute format('grant select, insert, update, delete on public.%I to reachout_writer', t);
  end loop;
end
$$;
